In [2]:
import numpy as np

#### 2.1 numpy array motivation

In [2]:
prices = []
N = 60*60*24*365
for i in range(N):
    prices.append(100 + i/100)

In [4]:
prices[:5]

[100.0, 100.01, 100.02, 100.03, 100.04]

In [5]:
avg = 0.0
for p in prices:
    avg += p/len(prices)

print(avg)

157779.995


In [8]:
prices_np = 100 + np.arange(N)/100
prices_np[:5]

array([100.  , 100.01, 100.02, 100.03, 100.04])

In [9]:
avg = np.mean(prices_np)
avg

157779.995

#### 2.2 numpy array basics

In [3]:
arr = np.array([10, 20, 30 ,40, 50])

In [4]:
arr

array([10, 20, 30, 40, 50])

In [5]:
arr.ndim

1

In [6]:
arr.shape

(5,)

In [7]:
arr_2d = np.array([
    [10, 20, 30, 40, 50],
    [100, 200, 300, 400, 500]
])
arr_2d

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [8]:
arr_2d.ndim

2

In [10]:
arr_2d.shape

(2, 5)

In [11]:
len(arr_2d)

2

In [12]:
arr_2d.size

10

In [13]:
arr_2d.dtype

dtype('int64')

In [14]:
# mixed types get converted
foo = np.array([1.0, "Huhu", 123])
foo.dtype

dtype('<U32')

In [17]:
foo[1] = "Ihr naht euch wieder schwankende Gestalten, die früh sich einst"

In [18]:
foo

array(['1.0', 'Ihr naht euch wieder schwankende', '123'], dtype='<U32')

In [20]:
np.array([
    [10, 20, 30, 40, 50],
    [100, 200, 300, 400]
], dtype=object)

array([list([10, 20, 30, 40, 50]), list([100, 200, 300, 400])],
      dtype=object)

#### 2.3 creating numpy arrays

In [21]:
np.zeros(25)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(shape=(2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.full(shape=(2,3), fill_value='dudel')

array([['dudel', 'dudel', 'dudel'],
       ['dudel', 'dudel', 'dudel']], dtype='<U5')

In [24]:
np.arange(start=1, stop=5, step=1)

array([1, 2, 3, 4])

In [25]:
np.random.randint(low=1, high=7, size=(2,3))

array([[3, 2, 2],
       [4, 5, 3]])

In [27]:
# lottozahlen
np.random.randint(low=1, high=50, size=6)

array([20, 22,  5, 18, 19, 43])

#### 2.4 Indexing

In [30]:
lz = np.arange(1, 25)

In [31]:
lz[0]

1

In [32]:
lz[-1]

24

In [33]:
# prapagating new values to a series of indeces
lz[[1, 2, 3]] = [100, 200, 300]
lz[1:4]

array([100, 200, 300])

#### 2.5 Indexing multidimensional arrays

In [34]:
zoo = np.array([
    [
        [10, 20],
        [30, 40],
        [50, 60],
    ],
    [
        [11, 12],
        [13, 14],
        [15, 16],
    ]
])

In [35]:
zoo

array([[[10, 20],
        [30, 40],
        [50, 60]],

       [[11, 12],
        [13, 14],
        [15, 16]]])

In [36]:
zoo[0,:, 1] = 5

In [37]:
zoo

array([[[10,  5],
        [30,  5],
        [50,  5]],

       [[11, 12],
        [13, 14],
        [15, 16]]])

#### 2.6 Basic math

In [38]:
dudel = np.array([[4, 3],[1, 0]])
peng  = np.array([[1, 2],[3, 4]])

In [41]:
print(dudel + peng, '\n')
print(dudel - peng, '\n')
print(dudel * peng, '\n')
print(dudel / peng, '\n')

[[5 5]
 [4 4]] 

[[ 3  1]
 [-2 -4]] 

[[4 6]
 [3 0]] 

[[4.         1.5       ]
 [0.33333333 0.        ]] 



In [42]:
dudel + 7

array([[11, 10],
       [ 8,  7]])

### Challenge #1

#### Setup
With your high school reunion fast approaching, you decide to get in #### shape and lose some weight.
You record your weight every day for five weeks starting on a Monday. #### Given these daily weights,
build an array with your average weight per weekend.

In [43]:
dailywts = 185 - np.arange(5*7)/5
dailywts

array([185. , 184.8, 184.6, 184.4, 184.2, 184. , 183.8, 183.6, 183.4,
       183.2, 183. , 182.8, 182.6, 182.4, 182.2, 182. , 181.8, 181.6,
       181.4, 181.2, 181. , 180.8, 180.6, 180.4, 180.2, 180. , 179.8,
       179.6, 179.4, 179.2, 179. , 178.8, 178.6, 178.4, 178.2])

(Your goal is to build a 5-element array where each value gives your average weight on the
corresponding weekend.)

In [50]:
weeks = dailywts.reshape(5,7)

In [56]:
weeks

array([[185. , 184.8, 184.6, 184.4, 184.2, 184. , 183.8],
       [183.6, 183.4, 183.2, 183. , 182.8, 182.6, 182.4],
       [182.2, 182. , 181.8, 181.6, 181.4, 181.2, 181. ],
       [180.8, 180.6, 180.4, 180.2, 180. , 179.8, 179.6],
       [179.4, 179.2, 179. , 178.8, 178.6, 178.4, 178.2]])

In [59]:
weeks[:, 5:7]

array([[184. , 183.8],
       [182.6, 182.4],
       [181.2, 181. ],
       [179.8, 179.6],
       [178.4, 178.2]])

In [63]:
(weeks[:, 5] + weeks[:, 6]) / 2

array([183.9, 182.5, 181.1, 179.7, 178.3])

#### Setup
After binge watching the discovery channel, you ditch your job as a trial lawyer to become a gold miner.
You decide to prospect five locations underneath a 7x7 grid of land. How much gold do you uncover at each location?

In [66]:
np.random.seed(5555)
gold = np.random.randint(low=0, high=10, size=(7,7))
gold

array([[2, 3, 0, 5, 2, 0, 3],
       [8, 8, 0, 7, 1, 5, 3],
       [0, 1, 6, 2, 1, 4, 5],
       [4, 0, 8, 9, 9, 8, 7],
       [4, 2, 7, 0, 7, 2, 1],
       [9, 8, 9, 2, 5, 0, 8],
       [1, 9, 8, 2, 6, 4, 3]])

In [67]:
locs = np.array([
    [0,4],
    [2,2],
    [2,3],
    [5,1],
    [6,3]
])

In [ ]:
gold[:, locs]